ci-dev:
    cargo check --quiet --workspace --all-targets
    cargo check --quiet --workspace --all-features --lib --target wasm32-unknown-unknown
    cargo fmt --all -- --check
    cargo clippy --quiet --workspace --all-targets --all-features --  -D warnings -W clippy::all
    trunk build